services:
  nerkhbaz-api:
    build:
      context: .
      dockerfile: Dockerfile

    image: nerkhbaz-api:latest
    container_name: nerkhbaz-api

    depends_on:
      - redis

    ports:
      - "23959:25414"

    environment:
      SPRING_PROFILES_ACTIVE: prod
      MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
      NAVASAN_API_KEY: ${NAVASAN_API_KEY}

    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: nerkhbaz-redis

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes

    restart: unless-stopped

volumes:
  redis_data: