services:
  nerkhbaz-api:
    build:
      context: .
      dockerfile: Dockerfile

    image: nerkhbaz-api:latest
    container_name: nerkhbaz-api

    depends_on:
      - mongodb

    ports:
      - "23959:25414"

    environment:
      SPRING_PROFILES_ACTIVE: prod
      MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
      NAVASAN_API_KEY: ${NAVASAN_API_KEY}
      TZ: Asia/Tehran

    restart: unless-stopped

  mongodb:
    image: mongo:4.4
    container_name: nerkhbaz-mongodb

    ports:
      - "65030:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    volumes:
      - mongodb_data:/data/db

    restart: unless-stopped

volumes:
  mongodb_data: