spring.application.name=Nerkhbaz-API
server.port=25414
server.servlet.context-path=/api/v1/nerkhbaz

navasan.api-key=${NAVASAN_API_KEY}
spring.mongodb.uri=${MONGO_CONNECTION_STRING}

spring.cache.type=redis
spring.data.redis.host=redis
spring.data.redis.port=6379